# -*- coding: utf-8 -*-
"""Pytorch Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDErUkcMrxSylW_iOirJB_S997XqKeea
"""

import torch
import numpy as np
torch.manual_seed(1234)

"""##Tensors
#####- scalar is single number
#####- vector is a 2D array of numbers
#####- Tensors are N-D arrays of numbers
"""

def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

describe(torch.Tensor(3, 3))

describe(torch.randn(5, 3))

x = torch.arange(6).view(2,3)
describe(x)

x = torch.arange(0, 8)
print(x)

x = torch.arange(0, 20)

print(x.view(1, 20))
print(x.view(2, 10))
print(x.view(4, 5))
print(x.view(5, 4))
print(x.view(10, 2))
print(x.view(20, 1))

x = torch.arange(12).view(3, 4)
print(x.shape)

x = x.unsqueeze(dim=1)
print(x.shape)

x = x.squeeze()
print(x.shape)

print(torch.cuda.is_available())